// action type GET ALL PRODUCT
export const SEND_PRODUCTSLIST_REQUEST = "SEND_PRODUCTSLIST_REQUEST";
export const RECEIVE_PRODUCTSLIST_RESPONSE = "RECEIVE_PRODUCTSLIST_RESPONSE";
export const RECEIVE_PRODUCTSLIST_ERROR = "RECEIVE_PRODUCTSLIST_ERROR";

// action type GET PRODUCT Details
export const SEND_PRODUCT_DETAILS_REQUEST = "SEND_PRODUCT_DETAILS_REQUEST";
export const RECEIVE_PRODUCT_DETAILS_RESPONSE = "RECEIVE_PRODUCT_DETAILS_RESPONSE";
export const RECEIVE_PRODUCT_DETAILS_ERROR = "RECEIVE_PRODUCT_DETAILS_ERROR";