// action type GET ALL PRODUCT
export const SEND_PRODUCTSLIST_REQUEST = "SEND_PRODUCTSLIST_REQUEST";
export const RECEIVE_PRODUCTSLIST_RESPONSE = "RECEIVE_PRODUCTSLIST_RESPONSE";
export const RECEIVE_PRODUCTSLIST_ERROR = "RECEIVE_PRODUCTSLIST_ERROR";

// action type GET PRODUCT Details
export const SEND_PRODUCT_DETAILS_REQUEST = "SEND_PRODUCT_DETAILS_REQUEST";
export const RECEIVE_PRODUCT_DETAILS_RESPONSE = "RECEIVE_PRODUCT_DETAILS_RESPONSE";
export const RECEIVE_PRODUCT_DETAILS_ERROR = "RECEIVE_PRODUCT_DETAILS_ERROR";

// action type Add To Card
export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_UPDATE_ITEM = 'CART_UPDATE_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';

// action type Add To WishList
export const ADD_ITEM_WISHLIST = "ADD_ITEM_WISHLIST";

// action type Search in products
export const SEARCH_PRODUCTS_REQUEST = "SEARCH_PRODUCTS_REQUEST";
export const FILTER_BY_MULTI_RANGE_REQUEST = "FILTER_BY_MULTI_RANGE_REQUEST"
export const FILTER_BY_CATEGORY_REQUEST = "FILTER_BY_CATEGORY_REQUEST"
export const FILTER_BY_BRAND_REQUEST = "FILTER_BY_BRAND_REQUEST"
export const FILTER_BY_RATING_REQUEST = "FILTER_BY_RATING_REQUEST"
export const FILTER_BY_STOCK_REQUEST = "FILTER_BY_IN_STOCK_REQUEST"
export const FILTER_BY_SEARCH_REQUEST = "FILTER_BY_SEARCH_REQUEST"
export const SORT_BY_PRICE_REQUEST = "SORT_BY_PRICE_REQUEST"
export const CLEAR_FILTERS_REQUEST = "CLEAR_FILTERS_REQUEST"