// action type GET ALL PRODUCT
export const SEND_PRODUCTSLIST_REQUEST = "SEND_PRODUCTSLIST_REQUEST";
export const RECEIVE_PRODUCTSLIST_RESPONSE = "RECEIVE_PRODUCTSLIST_RESPONSE";
export const RECEIVE_PRODUCTSLIST_ERROR = "RECEIVE_PRODUCTSLIST_ERROR";